#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Apr  8 12:37:03 2025

@author: sergi
"""

import pandas as pd
import numpy as np

historic = pd.read_pickle('historic.pkl')

'''
#The dataframe generated by webscraping was cleaned using the following commented lines:

historic.rename(columns =  {'Unnamed: 3' : 'Team', 'Unnamed: 1' : 'Pos.'}, inplace = True)
historic.drop(columns = ['Unnamed: 0', 'Unnamed: 2'], inplace = True)

historic.to_pickle('historic.pkl')
'''
#W-D-L records are rescaled as probabilities
historic['PW'] = historic['W']/historic['P']
historic['PD'] = historic['D']/historic['P']
historic['PL'] = historic['L']/historic['P']

#Probabilities are put in logarithm form. Using base 3 so maximum possible entropy is 1.
historic['logPW'] = np.log2(historic['PW'])/np.log2(3)
historic['logPD'] = np.log2(historic['PD'])/np.log2(3)
historic['logPL'] = np.log2(historic['PL'])/np.log2(3)

historic.replace(-np.inf, 0, inplace = True) #Dealing with infinities caused by log(0)
np.seterr(divide='ignore', invalid='ignore') #Ignore warnings due to np.log2 infinites that have just been addressed

#Shannon entropy is computed
historic['H'] = - historic['PW']*historic['logPW'] - historic['PD']*historic['logPD'] - historic['PL']*historic['logPL']

#Aggregate data of entropy by team and season
Prova = historic.groupby(['Temp', 'Team'], as_index = False).agg(Entropia = ('H','max'))

#Maximum entropy by season
Maxims = historic.loc[historic.groupby(['Temp'])['H'].idxmax(), ['Temp', 'Team', 'H']].rename(columns = {'H': 'Entropia'})

#Maximum entropy by team. It does not take into account rebrandings/name changes 
Equips = historic.loc[historic.groupby(['Team'])['H'].idxmax(), ['Temp', 'Team', 'H']].rename(columns = {'H': 'Entropia'})

'''Comparison to 19-0-19 record (Jensen-Shannon distance)'''
#Compute M distribution
historic['MW'] = (historic['W']+0.5*historic['P'])/(2*historic['P'])
historic['MD'] = historic['D']/(2*historic['P'])
historic['ML'] = (historic['L']+0.5*historic['P'])/(2*historic['P'])

historic['logPMW'] = np.log2(historic['PW']/historic['MW'])
historic['logPMD'] = np.log2(historic['PD']/historic['MD'])
historic['logPML'] = np.log2(historic['PL']/historic['ML'])

historic.replace([np.inf, np.nan, -np.inf], 0, inplace = True) #More infinities and nans addressed

#Compute d(P || M) Kullback distance
historic['dPM'] = historic['PW']*historic['logPMW'] + historic['PD']*historic['logPMD'] + historic['PL']*historic['logPML']

#compute d(Q || M) Kullback distance
historic['dQM'] = 0.5*np.log2(0.5/historic['MW']) + 0.5*np.log2(0.5/historic['ML'])

#Compute JS distance
historic['JSD'] = 0.5*(historic['dPM'] + historic['dQM'])

#Aggregate data of JSD by team and season
ProvaJDS = historic.groupby(['Temp', 'Team'], as_index = False).agg(Entropia = ('JSD','max'))

#Maximum JSD by season
MinimsJDS = historic.loc[historic.groupby(['Temp'])['JSD'].idxmin(), ['Temp', 'Team', 'JSD']].rename(columns = {'Temp': 'Season'})

#Maximum JSD by team. It does not take into account rebrandings/name changes 
EquipsJDS = historic.loc[historic.groupby(['Team'])['JSD'].idxmin(), ['Temp', 'Team', 'JSD']]

top10 = MinimsJDS.sort_values('JSD').head(10).reset_index(drop=True).rename(columns={'index': 'rank'})
top10.index = top10.index + 1
print('The top 10 most unpredictable LaLiga teams are:')
print(top10)